config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  root 'books#index'
  get '/help', to:'static_pages#help'
  get '/about', to:'static_pages#about'
  get '/contact', to:'static_pages#contact'
  get '/signup', to:'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/categories',   to: 'categories#index'
  post '/categories',   to: 'categories#create'
  resources :users
  resources :books do
    member do
      patch 'checkin'
      patch 'checkout'
    end
  end

end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :number, presence: true, uniqueness: true
  validates :description, length: {maximum: 255}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :checked_out_by, presence: true, unless: :available, length: {maximum: 255},
    format: { with: VALID_EMAIL_REGEX }

  def self.checked_out_search()
    where("available = false")
  end

  def self.category_search(category)
    where("'#{category}' = ANY (categories)")
  end

  def self.author_search(author)
    where("author ILIKE ?", "%#{author}%")
  end

  def self.title_search(title)
    where("title ILIKE ?", "%#{title}%")
  end

  def self.to_csv
    CSV.generate do |csv|
      column_names = %w(number title author categories description)
      csv << column_names
      all.sort_by{|e| e[:number]}.each do |result|
        csv << result.attributes.values_at(*column_names)
      end
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :admin_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:checkout, :checkin]

  def index
    respond_to do |format|
      format.html {
        @categories = Category.all
        if params[:checked_out] == "true"
          @books = Book.checked_out_search.order("number ASC")
        elsif params[:category]
          @books = Book.category_search(params[:category]).order("number ASC")
        elsif params[:title]
          @books = Book.title_search(params[:title]).order("number ASC")
        elsif params[:author]
          @books = Book.author_search(params[:author]).order("number ASC")
        else
          @books = Book.paginate(page:params[:page]).order("number ASC")
        end
      }
      format.csv {
        @books = Book.all
        send_data @books.to_csv
      }
    end
  end

  def csv
    @books = Book.all;
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
    @categories = Category.all
  end

  def create
    @categories = Category.all
    @book = Book.new(fix_categories(book_params, @categories))
    if @book.save
      flash.now[:success] = "#{@book.title} successfully added"
      redirect_to @book
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all
    @book = Book.find(params[:id])
  end

  def update
    @categories = Category.all
    @book = Book.find(params[:id])
    if @book.update_attributes(fix_categories(book_params, @categories))
      flash[:success] = "#{@book.title} successfully updated"
      redirect_to @book
    else
      render 'edit'
    end
  end

  def checkout
    @book = Book.find(params[:id])
    if @book.update_attributes(checkout_params)
      flash[:success] = "you checked out #{@book.title}!"
      redirect_to @book
    else
      flash[:danger] = "Valid email required to checkout book"
      redirect_to @book
    end
  end

  def checkin
    @book = Book.find(params[:id])
    if @book.update_attributes({:available => true, :checked_out_by => ""})
      flash[:success] = "Thanks for checking #{@book.title} back in!"
      redirect_to @book
    else
      render @book
    end
  end

  def destroy
    book_to_destroy = Book.find(params[:id])
    flash[:success] = "#{book_to_destroy.title} deleted"
    book_to_destroy.destroy
    redirect_to books_url
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :number, :description, categories: [])
  end

  def fix_categories(params, all_categories)
    if params[:categories]
      params[:categories] = params[:categories].drop(1)
    end
    params
  end

  def checkout_params
    params.require(:book).permit(:checked_out_by).merge({:available => false})
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<li>
  <%= link_to "#{book.title}  -  #{book.number}", book %>
  <% if !book.available %>
    <% if current_user && current_user.admin? %>
      <%= "Checked out by #{book.checked_out_by}" %>
    <% else %>
      Checked Out
    <% end %>
  <% end %>
</li>

app/views/books/_book_error_messages.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@book.errors.count, "error") %>.
    </div>
    <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/_books_unpaginated.html.erb
<div class="row">
  <div class="col-sm-4">
    <%= render "library_nav" %>
  </div>
  <div class="col-sm-8">
    <ul class="books">
      <%= render @books %>
    </ul>
  </div>
</div>

app/views/books/_category.erb
<li>
  <%= category %>
</li>

app/views/books/_library_nav.html.erb
<div class="books_nav">
  <div>
    <%= link_to "All Books", "/books", class: "books_category-link " %>
    <%= link_to "Checked Out Books", "/books?checked_out=true", class: "books_category-link " %>
    <h2>Search library</h2>
    <%= form_tag(books_path, :method => "get", class: "books_search-form") do %>
      <%= content_tag(:div, class: "form-group") do %>
        <%= text_field_tag :title, params[:title], class: "form-control", placeholder: "Search By Title" %>
      <% end %>
      <%= button_tag "Search By Title", class: "btn btn-default" %>
    <% end %>
    <%= form_tag(books_path, :method => "get", class: "books_search-form") do %>
      <%= content_tag(:div, class: "form-group") do %>
        <%= text_field_tag :author, params[:author], class: "form-control", placeholder: "Search By Author" %>
      <% end %>
      <%= button_tag "Search By Author", class: "btn btn-default" %>
    <% end %>
  </div>
  <h2>Browse by category</h2>
  <% @categories.each do |c| %>
    <%= link_to c.name, "/books?category=#{c.name}", class: "books_category-link " %>
  <% end %>
</div>

app/views/books/edit.html.erb
<% provide(:title, 'Edit Book') %>
<h1>Update Book</h1>
<%= simple_form_for @book do |f| %>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <%= render 'book_error_messages' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3 col-md-offset-1">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.label :author %>
      <%= f.text_field :author, class: 'form-control' %>
      <%= f.label :number %>
      <%= f.text_field :number, class: 'form-control' %>
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="col-md-8">
      <%= f.input :categories, wrapper_html: { class: 'category_checkboxes' }, collection: @categories, as: :check_boxes, value_method: :name %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2 col-md-offset-5">
      <%= f.submit "Edit Book", class: "category_submit_button btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/books/index.html.erb
<% if params[:checked_out] %>
  <% provide(:title, "Checked out books")%>
  <h1> Checked out books </h1>
  <%= render "books_unpaginated" %>
<% elsif params[:author] %>
  <% provide(:title, params[:author])%>
  <h1> <%= params[:author] %> </h1>
  <%= render "books_unpaginated" %>
<% elsif params[:title] %>
  <% provide(:title, params[:title])%>
  <h1> <%= params[:title] %> </h1>
  <%= render "books_unpaginated" %>
<% elsif params[:category] %>
  <% provide(:title, params[:category])%>
  <h1> <%= params[:category] %> </h1>
  <%= render "books_unpaginated" %>
<% else %>
  <% provide(:title, 'All books') %>
  <h1> All Books </h1>
  <div class="row">
    <div class="col-sm-4">
      <%= render "library_nav" %>
    </div>
    <div class="col-sm-8">
      <%= will_paginate %>
      <ul class="books">
        <%= render @books %>
      </ul>
      <%= will_paginate %>
    </div>
  </div>
<% end %>

app/views/books/new.html.erb
<% provide(:title, 'Add book') %>
<h1>Add Book</h1>
<%= simple_form_for @book do |f| %>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <%= render 'book_error_messages' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3 col-md-offset-1">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.label :author %>
      <%= f.text_field :author, class: 'form-control' %>
      <%= f.label :number %>
      <%= f.text_field :number, class: 'form-control' %>
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="col-md-8">
      <%= f.input :categories, wrapper_html: { class: 'category_checkboxes' }, collection: @categories, as: :check_boxes, value_method: :name %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2 col-md-offset-5">
      <%= f.submit "Add Book", class: "category_submit_button category_submit_button btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/books/show.html.erb
<% provide(:title, @book.title) %>
<div class="row">
  <div class="col-md-5 col-md-offset-1">
    <h1 class="book-page_title">
      <%= @book.title %>
    </h1>
    <h2 class="book-page_author">
      <%= "Author: #{@book.author}" %>
    </h2>
    <h2 class="book-page_number">
      <%= "Ref #: #{@book.number}" %>
    </h2>
    <% unless @book.description.empty? %>
      <p><%= "Description: #{@book.description}" %></p>
    <% end %>
    <% unless @book.categories.empty? %>
      <h3 class="book-page_categories_label">
        Categories
    </h3>
      <ul class="book-page_categories">
        <% @book.categories.each do |c| %>
          <%= render 'category', :category => c  %>
        <% end %>
      </ul>
    <% end %>
  </div>
  <% if logged_in? %>
    <div class="book_show_controls col-md-5">
      <% if @book.available %>
        <span class="book_show_available">This book is available!</span>
        <%= form_for @book, url: checkout_book_path(@book) do |f| %>
          <%= render 'book_error_messages' %>
          <%= f.label :checked_out_by, "Please enter your email to check out"%>
          <%= f.email_field :checked_out_by, class: 'form-control' %>
          <%= f.submit "Check Out Book", class: "book_show_button btn btn-primary" %>
        <% end %>
      <% else %>
        <% if current_user && current_user.admin? %>
          <%= "Checked out by #{@book.checked_out_by}" %>
        <% else %>
          <%= "This book is officially checked out. Is it back in the library? If so, go ahead and check it in"%>
        <% end %>
        <%= form_for @book, url: checkin_book_path(@book) do |f| %>
          <%= render 'book_error_messages' %>
          <%= f.submit "Check In Book", class: "book_show_button btn btn-primary" %>
        <% end %>
      <% end %>
      <% if current_user && current_user.admin? %>
        <%= link_to "Delete Book", @book, method: :delete, data: {confirm: "You sure?"}, class: "book_show_button btn btn-primary"%>
        <%= link_to "Edit Book", edit_book_path(@book), class: "book_show_button btn btn-primary"%>
      <% end %>
    </div>
  <% end %>
</div>